[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 14.0

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[shell]
args = ["--login"]
program = "/bin/bash"

[window]
opacity = 0.5

[window.padding]
x = 20
y = 20
